### ISSUE TITLE
What is the correct way to work with ObjectProphecy

### ISSUE THREAD

**Issue by ismailcherri** [psalm/phpunit-psalm-plugin#115]
Hi,
We have a lot of tests in our Symfony project which basically look like this

```php
class SomeServiceTest extends TestCase
{
    use ProphecyTrait;

    /**
     * @var OtherServiceInterface|ObjectProphecy
     */
    private $otherService;

    private SomeService $someService;

    protected function setUp(): void
    {
        $this->otherService = $this->prophesize(OtherServiceInterface::class);
        
		$this->someService = new SomeService(
            $this-otherService->reveal()
        );
    }

...

}
```

But in tests we get error when we try to use `willReturn()` method from Prophecy
```php
	$this-otherService->method()->willReturn($something);
```

we get:
```
psalm: PossiblyUndefinedMethod: Method OtherService::willReturn does not exist
```

Isn't the union type in the annotation states that both classes are valid for this property?

**Comment by cooperaj** [comment]
Mmm, sorry to bring this one back up but I can't get this to work. Adding a `/** @var ObjectProphecy<OtherInterface> $var` to my code just has Psalm tell me that this has already been inferred from the code.
So I figured I'd do `/** @var Mink|ObjectProphecy<Mink> $minkProphecy */` but this results in _MixedAssignment_ and _MixedMethodCall_ errors. I guess this makes sense but it still gets me no closer to having decent Psalm results in my test files.

**Comment by weirdan** [comment]
@cooperaj what does your test look like? Most likely you don't need to annotate your variables at all.
