### ISSUE TITLE
MockObject::method() return type

### ISSUE THREAD

**Issue by weirdan** [psalm/phpunit-psalm-plugin#2]
https://github.com/psalm/phpunit-psalm-plugin/blob/5fd3db0c48c208a49b008561c27d83d1d319e3ad/stubs/MockBuilder.php#L49

In PHPUnit 7.4 (probably all 7.x series) this returns `PHPUnit\Framework\MockObject\Builder\InvocationMocker`, not `static`. What PHPUnit version you were basing stubs on?

**Comment by muglug** [comment]
I'm basing it on PHPUnit 7.

It doesn't return `InvocationMocker`, AFAICT. I think `MockObject::method` is declared here: https://github.com/sebastianbergmann/phpunit-mock-objects/blob/f9756fd4f43f014cb2dca98deeaaa8ce5500a36e/src/Generator/mocked_class_method.tpl.dist

That method makes a call to `InvocationMocker`, but the result of the method call is still a `MockObject`.

That allows the following to be type-checked:

```php
$foo = $this->getMockBuilder(Foo::class)->getMock();
$foo->method('bar')->willReturn(true);
$this->assertTrue(SomeClass::someMethod($foo));
```

I may well be wrong, in which case @sebastianbergmann may strike me down

**Comment by weirdan** [comment]
> That method makes a call to InvocationMocker, but the result of the method call is still a MockObject.

Empirically: 

```php
        var_dump(get_class($this->createMock(\Psr\Log\LoggerInterface::class)->method('log')));
        // string(53) "PHPUnit\Framework\MockObject\Builder\InvocationMocker"    
```

Theoretically:
* The method you mentioned calls `$this->expects(new \PHPUnit\Framework\MockObject\Matcher\AnyInvokedCount)->method()` passing down all the arguments
* Expanding `$this->expects()` (defined here: https://github.com/sebastianbergmann/phpunit-mock-objects/blob/f9756fd4f43f014cb2dca98deeaaa8ce5500a36e/src/Generator/mocked_class.tpl.dist#L9 ) results in `$this->__phpunit_getInvocationMocker()->expects(new \PHPUnit\Framework\MockObject\Matcher\AnyInvokedCount)->method(...func_get_args())`
* `$this->__phpunit_getInvocationMocker()` returns `\PHPUnit\Framework\MockObject\InvocationMocker` (initialized here: https://github.com/sebastianbergmann/phpunit-mock-objects/blob/f9756fd4f43f014cb2dca98deeaaa8ce5500a36e/src/Generator/mocked_class.tpl.dist#L27 )
* `\PHPUnit\Framework\MockObject\InvocationMocker::expects()` (defined here: https://github.com/sebastianbergmann/phpunit-mock-objects/blob/f9756fd4f43f014cb2dca98deeaaa8ce5500a36e/src/InvocationMocker.php#L115) returns `PHPUnit\Framework\MockObject\Builder\InvocationMocker` 
* `PHPUnit\Framework\MockObject\Builder\InvocationMocker::method()` (defined here: https://github.com/sebastianbergmann/phpunit-mock-objects/blob/f9756fd4f43f014cb2dca98deeaaa8ce5500a36e/src/Builder/InvocationMocker.php#L257) returns `$this` - thus `PHPUnit\Framework\MockObject\Builder\InvocationMocker`

**Comment by weirdan** [comment]
```php
var_dump(get_class($this->getMockBuilder(\Psr\Log\LoggerInterface::class)->getMock()->method('log')));
// string(53) "PHPUnit\Framework\MockObject\Builder\InvocationMocker"  
```

**Comment by muglug** [comment]
I was very wrong and you were very right. Thanks for taking the time to research and fix.
