### ISSUE TITLE
Work properly in multithreaded mode

### ISSUE THREAD

**Issue by muglug** [psalm/phpunit-psalm-plugin#29]
With latest Psalm master one can just do 

```php
$codebase->methodExists($declaring_method_id, null, 'PHPUnit\Framework\TestSuite::run');
```

to reliably register a method as having been used, but looks like that doesn't work elsewhere

**Comment by weirdan** [comment]
I'm not sure, do you suggest to register all methods as used from unknown/hardcoded location? Wouldn't that render `--find-references-to` useless for those methods?

**Comment by muglug** [comment]
Yeah, it would render it useless for `PHPUnit\Framework\TestSuite::run`, but I don't imagine anyone would be too bothered.

**Comment by weirdan** [comment]
Ah, so you were talking about `test*` methods.
