### ISSUE TITLE
issue w/ TList being unexpected

### ISSUE THREAD

**Issue by SignpostMarv** [psalm/phpunit-psalm-plugin#41]
https://github.com/psalm/phpunit-psalm-plugin/blob/1dcd8ff7719b78b858d7560dd2d912a55272bfbc/hooks/TestCaseHandler.php#L380

`TestCaseHander::unionizeIterables()` seems to choke on `Psalm\Type\Atomic\TList`

presently at the dayjob, ~going to try and PR from the web interface.~ had to make two attempts to get a nice diff in the web interface: #42

**Comment by weirdan** [comment]
Fixed in #42
