### ISSUE TITLE
TestCaseHandler upstream bug

### ISSUE THREAD

**Issue by jguittard** [psalm/phpunit-psalm-plugin#55]
When leveraging Psalm plugin, there is a weird case where upstream crashes.

See context : https://travis-ci.org/Roave/psr-container-doctrine/jobs/654211817

**Comment by weirdan** [comment]
Fixed in 496c08f088d9e34e1947bca1de52b32b6571bad3 (released as [0.9.0](https://github.com/psalm/phpunit-psalm-plugin/releases/tag/0.9.0)).
