### ISSUE TITLE
TestCase::assertTrue(is_a(str, str, true)), TestCase::assertInstanceOf() & TypeCoercion, InvalidStringClass

### ISSUE THREAD

**Issue by SignpostMarv** [psalm/phpunit-psalm-plugin#7]
How cumbersome would it be for this plugin to decorate the variables being asserted with appropriate flags?

i.e. `TestCase::assertInstanceOf(class-string, $foo)` prior to `Bar($foo)` where the method signature is `Bar(WhateverTheClassStringWasInTheAssertion $obj)` and `$foo` is of type `WhateverTheClassStringWasInTheAssertion|null` results in `Argument ` of Bar cannot be null, possibly null value provided`

Similarly, when asserting that `is_a()` returns true, psalm is not made aware that `string $foo` is now `class-string<SomeThing> $foo`, triggering `InvalidStringClass` on invocation and `TypeCoercion` when `$foo` is later passed argument 1 to `TestCase::assertInstanceOf()`:

```php
function testThing(string $foo) : void {
    static::assertTrue(is_a($foo, SomeThing::class, true));
    $obj = new $type();
    /* actual test stuff here */
}
```

**Comment by SignpostMarv** [comment]
oh, p.s.; when a test calls a method that has a return signature of `T|null`, assertions "prove" it to be `T`, then the variable is passed to a method that accepts only `T` and not `T|null`, we get a `PossiblyNullArgument`.

**Comment by weirdan** [comment]
> i.e. TestCase::assertInstanceOf(class-string, $foo) prior to Bar($foo) where the method signature is Bar(WhateverTheClassStringWasInTheAssertion $obj) and $foo is of type WhateverTheClassStringWasInTheAssertion|null results in Argument of Bar cannot be null, possibly null value provided`

`assertInstanceOf` works for me just like you say you want it to:
![image](https://user-images.githubusercontent.com/57403/51796811-bfd17e00-2201-11e9-8fde-672e84f5f27d.png)

As a sanity check, are you sure you have this plugin installed and enabled? What does `psalm-plugin` show?

> Similarly, when asserting that is_a() returns true, psalm is not made aware that string $foo is now class-string<SomeThing> $foo

This I can confirm.

> when a test calls a method that has a return signature of `T|null`, assertions "prove" it to be `T`, then the variable is passed to a method that accepts only `T` and not `T|null`, we get a `PossiblyNullArgument`.

Isn't it the same as your first problem?

**Comment by SignpostMarv** [comment]
@weirdan I'm getting issues where comparing `class-string<Exception>` to `class-string<Exception>` goes a bit screwy. Will upload an example in a short while.

**Comment by SignpostMarv** [comment]
okay, when writing the example code from scratch I'm getting redundant conditions flagged up as expected, although now I'm getting an issue that I'm not 100% sure if it's an issue; `LessSpecificReturnStatement` and `MoreSpecificReturnType`.

Closing this and opening issue on psalm repo :D
